/* Automatically generated by './build/bin/build-entry.js' */

import Hello from './components/Hello';


const components = [
  Hello
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;
  components.map(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

module.exports = {
  version: '1.0.0',
  Hello
};

module.exports.default = module.exports;
